import type { HelpContent } from './en';

const help: HelpContent = {
  back: "Zurück zu DaysToCitizen",
  hero: {
    title: "So verfolgen Sie Ihre Tage für die kanadische Staatsbürgerschaft",
    introBefore: "In Kanada ist die Ansammlung ständiger Einwohner erforderlich",
    introBold: "1.095 Tage physische Präsenz",
    introAfter: "innerhalb eines Zeitraums von 5 Jahren vor der Beantragung der Staatsbürgerschaft. Dieser Leitfaden erklärt genau, wie IRCC diese Tage zählt und wie DaysToCitizen Ihnen hilft, sie ohne Tabellenkalkulationen zu verfolgen.",
  },
  requirement: {
    title: "Die IRCC-Anforderung an die physische Anwesenheit",
    p1Before: "Unter dem",
    p1Law: "Staatsbürgerschaftsgesetz",
    p1After: ", muss jeder Staatsbürgerschaftsbewerber nachweisen, dass er sich in den 5 Jahren unmittelbar vor seinem Antragsdatum mindestens 1.095 Tage (3 Jahre) in Kanada physisch aufgehalten hat. Dies wird auf fortlaufender Basis berechnet – das 5-Jahres-Fenster verschiebt sich mit Ihrem Bewerbungsdatum, nicht mit einem festen Kalenderzeitraum.",
    keyRuleTitle: "Wichtige Regel: Sowohl der Tag der Einreise als auch der Tag der Abreise zählen als volle Tage.",
    keyRuleBody: "Wenn Sie am 1. März nach Toronto fliegen und am 5. März wieder abfliegen, zählt das als 5 Tage – nicht als 3 oder 4. Dies ist einer der häufigsten Fehlzählungsfehler.",
    p2: "IRCC überprüft Ihre Anwesenheit anhand von Passstempeln, Reisedaten, Steuerunterlagen und anderen Dokumenten. Wenn Sie Ihre Tage zu niedrig oder zu hoch angeben – auch aus Versehen –, kann dies zur Ablehnung des Antrags oder zur Feststellung falscher Angaben führen.",
  },
  status: {
    title: "Daueraufenthaltstage im Vergleich zu anderen Statustagen",
    intro: "Nicht alle Tage in Kanada zählen gleichermaßen. Das Staatsbürgerschaftsgesetz unterscheidet zwischen der Zeit, die man als ständiger Einwohner verbringt, und der Zeit, die man mit einem anderen Einwanderungsstatus (Studentenvisum, Arbeitserlaubnis, Besucher, geschützte Person usw.) verbringt.",
    thStatus: "Status",
    thCounts: "Zählt gegen 1.095?",
    thRate: "Bewerten",
    prStatus: "Ständiger Wohnsitz",
    prCounts: "Ja",
    prRate: "1 Tag = 1 Tag",
    refugeeStatus: "Geschützte Person / Konventionsflüchtling",
    refugeeCounts: "Ja (teilweise)",
    refugeeRate: "2 Tage = 1 Tag (maximal 365 gutgeschrieben)",
    visitorStatus: "Student/Arbeitserlaubnis/Besucher",
    visitorCounts: "Ja (teilweise)",
    visitorRate: "2 Tage = 1 Tag (maximal 365 gutgeschrieben)",
    noneStatus: "Nicht autorisiert / Kein Status",
    noneCounts: "Nein",
    noneRate: "0",
    footer: "DaysToCitizen wendet diese Tarife automatisch an, wenn Sie jeden Aufenthalt protokollieren. Wählen Sie einfach Ihren Einwanderungsstatus für jeden Zeitraum aus und die Berechnung wird für Sie erledigt.",
  },
  howto: {
    title: "So verwenden Sie DaysToCitizen",
    step1Title: "Öffnen Sie die App – keine Anmeldung erforderlich.",
    step1Body: "Ihre Aufenthalte werden lokal in Ihrem Browser gespeichert. Erstellen Sie nur dann ein Konto, wenn Sie möchten, dass Ihre Daten geräteübergreifend synchronisiert werden.",
    step2Title: "Fügen Sie Ihre Aufenthalte in Kanada hinzu.",
    step2Body: "Geben Sie das Einreisedatum, das Ausreisedatum (lassen Sie das Feld leer, wenn Sie sich derzeit in Kanada befinden) und Ihren damaligen Einwanderungsstatus ein.",
    step3Title: "Lesen Sie Ihr Dashboard.",
    step3Body: "Die Countdown-Karte zeigt an, wie viele Tage Sie noch benötigen. Der Fortschrittsbalken zeigt Ihr 5-Jahres-Fenster. Auf den Statistikkarten werden die gutgeschriebenen Tage im Vergleich zur Gesamtzahl der Tage aufgeschlüsselt.",
    step4Title: "Aktualisieren Sie, während Sie reisen.",
    step4Body: "Fügen Sie bei jeder Rückkehr nach Kanada einen neuen Aufenthalt hinzu. Die Berechnung wird sofort aktualisiert.",
  },
  faq: {
    title: "Häufig gestellte Fragen",
    q1: "Zähle ich den Tag meiner Ankunft und den Tag meiner Abreise?",
    a1: "Ja. IRCC zählt sowohl den Ankunftstag als auch den Abreisetag als volle Anwesenheitstage. Eine Reise von Montag bis Freitag dauert 5 Tage, nicht 4 oder 3. DaysToCitizen verwendet dieselbe inklusive Zählmethode.",
    q2: "Was wäre, wenn ich in Kanada wäre, bevor ich einen ständigen Wohnsitz erhalte?",
    a2: "Die Zeit, die Sie vor Ihrem PR-Termin in Kanada verbringen, kann im Verhältnis 2 zu 1 angerechnet werden (maximal 365 gutgeschriebene Tage). Wählen Sie „Anderer Status“ aus, wenn Sie diese Aufenthalte protokollieren, und DaysToCitizen wendet den korrekten Tarif an.",
    a2ExampleTitle: 'Beispiel',
    a2ExampleLine1: 'Jan 2023 – Mrz 2024 → Wählen Sie „Anderer Status" (Visum/Arbeit/Studium). Diese 15 Monate zählen im Verhältnis 2:1.',
    a2ExampleLine2: 'Mrz 2024 – Jan 2026 → Wählen Sie „Permanent Resident". Diese 22 Monate zählen vollständig (1:1).',
    q3: "Zählt die Remote-Arbeit für ein kanadisches Unternehmen im Ausland?",
    a3: "Nein. Physische Anwesenheit bedeutet, dass Sie sich physisch in Kanada aufhalten müssen. Fernarbeit von einem anderen Land aus wird – selbst für einen kanadischen Arbeitgeber – nicht auf Ihre 1.095 Tage angerechnet.",
    q4: "Kann ich einen Antrag stellen, bevor genau 1.095 Tage erreicht sind?",
    a4: "Nein. Sie müssen vor Ihrem Bewerbungsdatum mindestens 1.095 Tage angerechnet haben. Das IRCC wird dies überprüfen und Anträge ablehnen, die auch nur einen einzigen Tag zu kurz kommen.",
    q5: "Welche Dokumente verwendet das IRCC zur Überprüfung der Anwesenheit?",
    a5: "IRCC kann eine beliebige Kombination aus Reisepassstempeln, Flugrouten, Steuererklärungen (T1 Allgemein), Beschäftigungsunterlagen, Schulunterlagen, Mietverträgen und Kontoauszügen anfordern. Es wird dringend empfohlen, Aufzeichnungen über alle Reisen zu führen.",
    q6: "Ist DaysToCitizen ein offizielles IRCC-Tool?",
    a6Before: "Nein. DaysToCitizen ist ein unabhängiges Open-Source-Tool, das Einwanderern dabei helfen soll, ihre eigenen Aufzeichnungen zu verfolgen. Es ist nicht mit der kanadischen Regierung verbunden. Überprüfen Sie Ihre Bewerbungsdaten immer durch den Beamten",
    a6Link: "IRCC",
    a6After: "Website, bevor Sie Ihre Bewerbung einreichen.",
    q7: "Sind meine Daten privat?",
    a7: "Ja. Die Daten der Gastbenutzer verbleiben vollständig in ihrem Browser (localStorage) – es wird nichts an einen Server gesendet. Die Daten registrierter Benutzer werden sicher in Kanada gespeichert (AWS ca-central-1) und niemals weitergegeben oder verkauft. Die App ist Open Source und kann selbst gehostet werden.",
  },
  mistakes: {
    title: "Häufige Fehler beim Zählen, die Sie vermeiden sollten",
    m1: "Bei exklusiver Zählung (Ankunfts-/Abreisetage nicht einbeziehen) – zählen Sie immer beide Enden.",
    m2: "Vergessen Sie Kurztrips – selbst ein Wochenende jenseits der Grenze zerstört Ihre Erfolgssträhne.",
    m3: "Keine Protokollierung der Vor-PR-Zeit – diese Tage zählen zu 50 % und können bis zu 365 gutgeschriebene Tage ergeben.",
    m4: "Vorausgesetzt, das 5-Jahres-Fenster ist festgelegt – es verschiebt sich mit Ihrem Bewerbungsdatum.",
    m5: "Absenden, bevor genau 1.095 erreicht sind – warten Sie, bis das Dashboard 0 verbleibende Tage anzeigt.",
  },
  cta: {
    title: "Fangen Sie an, Ihre Tage zu verfolgen",
    subtitle: "Kostenlos, privat und keine Einrichtung erforderlich. Funktioniert in 23 Sprachen.",
    button: "Tage der offenen Tür für Bürger →",
  },
};

export default help;
