import type { HelpContent } from './en';

const help: HelpContent = {
  back: "Volver a DaysToCitizen",
  hero: {
    title: "Cómo realizar un seguimiento de sus días para la ciudadanía canadiense",
    introBefore: "Canadá exige que los residentes permanentes acumulen",
    introBold: "1.095 días de presencia física",
    introAfter: "dentro de cualquier período de 5 años antes de solicitar la ciudadanía. Esta guía explica exactamente cómo el IRCC cuenta esos días y cómo DaysToCitizen le ayuda a realizar un seguimiento sin hojas de cálculo.",
  },
  requirement: {
    title: "El requisito de presencia física del IRCC",
    p1Before: "bajo el",
    p1Law: "Ley de ciudadanía",
    p1After: ", cada solicitante de ciudadanía debe demostrar que estuvo físicamente presente en Canadá durante al menos 1095 días (3 años) de los 5 años inmediatamente anteriores a la fecha de su solicitud. Esto se calcula de forma continua: el período de 5 años avanza con la fecha de su solicitud, no con un período calendario fijo.",
    keyRuleTitle: "Regla clave: tanto el día de entrada como el de salida cuentan como días completos.",
    keyRuleBody: "Si vuela a Toronto el 1 de marzo y sale el 5 de marzo, eso cuenta como 5 días, no 3 o 4. Este es uno de los errores de conteo más comunes.",
    p2: "El IRCC verifica su presencia mediante sellos de pasaporte, historial de viajes, registros de impuestos y otros documentos. Subestimar o exagerar sus días, incluso accidentalmente, puede resultar en el rechazo de la solicitud o en la conclusión de tergiversación.",
  },
  status: {
    title: "Días de residente permanente frente a otros días de estatus",
    intro: "No todos los días en Canadá cuentan por igual. La Ley de Ciudadanía distingue entre el tiempo pasado como Residente Permanente y el tiempo pasado bajo otros estatus migratorios (visa de estudiante, permiso de trabajo, visitante, persona protegida, etc.).",
    thStatus: "Estado",
    thCounts: "¿Cuenta hasta 1.095?",
    thRate: "Tarifa",
    prStatus: "Residente Permanente",
    prCounts: "si",
    prRate: "1 día = 1 día",
    refugeeStatus: "Persona Protegida / Refugiado de Convención",
    refugeeCounts: "Sí (parcial)",
    refugeeRate: "2 días = 1 día (máximo 365 acreditados)",
    visitorStatus: "Estudiante / Permiso de Trabajo / Visitante",
    visitorCounts: "Sí (parcial)",
    visitorRate: "2 días = 1 día (máximo 365 acreditados)",
    noneStatus: "No autorizado/sin estado",
    noneCounts: "No",
    noneRate: "0",
    footer: "DaysToCitizen aplica estas tarifas automáticamente cuando registra cada estadía. Simplemente seleccione su estado migratorio para cada período y los cálculos se manejarán por usted.",
  },
  howto: {
    title: "Cómo utilizar DaysToCitizen",
    step1Title: "Abra la aplicación; no es necesario registrarse.",
    step1Body: "Tus estancias se guardan localmente en tu navegador. Cree una cuenta solo si desea sincronizar sus datos entre dispositivos.",
    step2Title: "Añade tus estancias en Canadá.",
    step2Body: "Ingrese la fecha de entrada, la fecha de salida (déjela en blanco si se encuentra actualmente en Canadá) y su estado migratorio en ese momento.",
    step3Title: "Lea su tablero.",
    step3Body: "La tarjeta de cuenta atrás muestra cuántos días más necesitas. La barra de progreso muestra su ventana de 5 años. Las tarjetas de estadísticas desglosan los días acreditados frente al total.",
    step4Title: "Actualízate mientras viajas.",
    step4Body: "Añade una nueva estancia cada vez que regreses a Canadá. El cálculo se actualiza instantáneamente.",
  },
  faq: {
    title: "Preguntas frecuentes",
    q1: "¿Cuento el día que llego y el día que salgo?",
    a1: "Sí. El IRCC cuenta tanto el día de llegada como el día de salida como días completos de presencia. Un viaje de lunes a viernes dura 5 días, no 4 o 3. DaysToCitizen utiliza este mismo método de conteo inclusivo.",
    q2: "¿Qué pasa si estuve en Canadá antes de convertirme en residente permanente?",
    a2: "El tiempo pasado en Canadá antes de su fecha de PR puede contar a una tarifa de 2 por 1 (máximo 365 días acreditados). Seleccione \"Otro estado\" al registrar esas estadías y DaysToCitizen aplicará la tarifa correcta.",
    q3: "¿Cuenta trabajar de forma remota para una empresa canadiense en el extranjero?",
    a3: "No. Presencia física significa que debes estar físicamente en Canadá. Trabajar de forma remota desde otro país, incluso para un empleador canadiense, no cuenta para sus 1095 días.",
    q4: "¿Puedo presentar la solicitud antes de cumplir exactamente 1.095 días?",
    a4: "No. Debe tener al menos 1,095 días acreditados antes de la fecha de su solicitud. El IRCC verificará esto y rechazará las solicitudes que se queden cortas, incluso por un solo día.",
    q5: "¿Qué documentos utiliza el IRCC para verificar la presencia?",
    a5: "El IRCC puede solicitar cualquier combinación de: sellos de viaje en pasaportes, itinerarios de vuelos, declaraciones de impuestos (T1 General), registros de empleo, registros escolares, contratos de arrendamiento y extractos bancarios. Se recomienda encarecidamente mantener registros de todos los viajes.",
    q6: "¿DaysToCitizen es una herramienta oficial del IRCC?",
    a6Before: "No. DaysToCitizen es una herramienta independiente de código abierto creada para ayudar a los inmigrantes a realizar un seguimiento de sus propios registros. No está afiliado al Gobierno de Canadá. Siempre verifique los detalles de su solicitud a través del sitio oficial.",
    a6Link: "IRCC",
    a6After: "sitio web antes de enviar su solicitud.",
    q7: "¿Mis datos son privados?",
    a7: "Sí. Los datos de los usuarios invitados permanecen completamente en su navegador (localStorage): no se envía nada a ningún servidor. Los datos de los usuarios registrados se almacenan de forma segura en Canadá (AWS ca-central-1) y nunca se comparten ni se venden. La aplicación es de código abierto y puede alojarse usted mismo.",
  },
  mistakes: {
    title: "Errores de conteo comunes que se deben evitar",
    m1: "Usando conteo exclusivo (sin incluir los días de llegada/salida): cuente siempre ambos extremos.",
    m2: "Olvidar los viajes cortos: incluso un fin de semana cruzando la frontera rompe tu racha.",
    m3: "No registrar el tiempo previo a las relaciones públicas: esos días cuentan al 50% y pueden sumar hasta 365 días acreditados.",
    m4: "Suponiendo que el período de 5 años sea fijo, se mueve con la fecha de su solicitud.",
    m5: "Enviar antes de llegar exactamente a 1095: espere hasta que el panel muestre 0 días restantes.",
  },
  cta: {
    title: "Comience a realizar un seguimiento de sus días",
    subtitle: "Gratis, privado y no requiere configuración. Funciona en 23 idiomas.",
    button: "Jornadas de puertas abiertas al ciudadano →",
  },
};

export default help;
