import type { HelpContent } from './en';

const help: HelpContent = {
  back: "Retour à DaysToCitizen",
  hero: {
    title: "Comment suivre vos jours pour la citoyenneté canadienne",
    introBefore: "Le Canada exige que les résidents permanents accumulent",
    introBold: "1 095 jours de présence physique",
    introAfter: "dans toute période de 5 ans avant de demander la citoyenneté. Ce guide explique exactement comment IRCC compte ces jours et comment DaysToCitizen vous aide à les suivre sans feuilles de calcul.",
  },
  requirement: {
    title: "L’exigence de présence physique d’IRCC",
    p1Before: "Sous le",
    p1Law: "Loi sur la citoyenneté",
    p1After: ", chaque demandeur de citoyenneté doit prouver qu'il était physiquement présent au Canada pendant au moins 1 095 jours (3 ans) sur les 5 ans précédant immédiatement la date de sa demande. Ceci est calculé sur une base glissante : la fenêtre de 5 ans évolue avec la date de votre candidature, et non avec une période calendaire fixe.",
    keyRuleTitle: "Règle clé : le jour de votre entrée et celui de votre départ comptent comme des jours complets.",
    keyRuleBody: "Si vous arrivez à Toronto le 1er mars et repartez le 5 mars, cela compte pour 5 jours, et non pour 3 ou 4. C'est l'une des erreurs de comptage les plus courantes.",
    p2: "IRCC vérifie votre présence à l'aide de tampons de passeport, d'historique de voyage, de dossiers fiscaux et d'autres documents. Sous-estimer ou surestimer vos jours – même accidentellement – ​​peut entraîner le refus de votre demande ou une conclusion de fausse déclaration.",
  },
  status: {
    title: "Jours de résidence permanente par rapport aux autres jours de statut",
    intro: "Au Canada, tous les jours ne comptent pas de la même manière. La Loi sur la citoyenneté fait la distinction entre le temps passé en tant que résident permanent et le temps passé sous d'autres statuts d'immigration (visa étudiant, permis de travail, visiteur, personne protégée, etc.).",
    thStatus: "Statut",
    thCounts: "Cela compte pour 1 095 ?",
    thRate: "Tarif",
    prStatus: "Résident Permanent",
    prCounts: "Oui",
    prRate: "1 jour = 1 jour",
    refugeeStatus: "Personne protégée / Réfugié au sens de la Convention",
    refugeeCounts: "Oui (partiel)",
    refugeeRate: "2 jours = 1 jour (max 365 crédités)",
    visitorStatus: "Étudiant / Permis de travail / Visiteur",
    visitorCounts: "Oui (partiel)",
    visitorRate: "2 jours = 1 jour (max 365 crédités)",
    noneStatus: "Non autorisé / Aucun statut",
    noneCounts: "Non",
    noneRate: "0",
    footer: "DaysToCitizen applique ces tarifs automatiquement lorsque vous enregistrez chaque séjour. Sélectionnez simplement votre statut d'immigration pour chaque période et le calcul est géré pour vous.",
  },
  howto: {
    title: "Comment utiliser DaysToCitizen",
    step1Title: "Ouvrez l'application - aucune inscription requise.",
    step1Body: "Vos séjours sont enregistrés localement dans votre navigateur. Créez un compte uniquement si vous souhaitez que vos données soient synchronisées sur tous les appareils.",
    step2Title: "Ajoutez vos séjours au Canada.",
    step2Body: "Entrez la date d'entrée, la date de sortie (laissez vide si vous êtes actuellement au Canada) et votre statut d'immigration à ce moment-là.",
    step3Title: "Lisez votre tableau de bord.",
    step3Body: "La carte du compte à rebours indique le nombre de jours supplémentaires dont vous avez besoin. La barre de progression affiche votre fenêtre de 5 ans. Les cartes de statistiques répartissent les jours crédités par rapport au nombre total de jours.",
    step4Title: "Mettez à jour pendant votre voyage.",
    step4Body: "Ajoutez un nouveau séjour à chaque fois que vous revenez au Canada. Le calcul est mis à jour instantanément.",
  },
  faq: {
    title: "Foire aux questions",
    q1: "Est-ce que je compte le jour de mon arrivée et le jour de mon départ ?",
    a1: "Oui. IRCC compte le jour d’arrivée et le jour de départ comme des jours complets de présence. Un trajet du lundi au vendredi dure 5 jours, et non 4 ou 3. DaysToCitizen utilise cette même méthode de comptage inclusive.",
    q2: "Et si j'étais au Canada avant de devenir résident permanent ?",
    a2: "Le temps passé au Canada avant votre date de RP peut compter à un taux de 2 pour 1 (maximum 365 jours crédités). Sélectionnez « Autre statut » lors de l'enregistrement de ces séjours et DaysToCitizen appliquera le tarif correct.",
    q3: "Est-ce que travailler à distance pour une entreprise canadienne à l'étranger compte?",
    a3: "Non. La présence physique signifie que vous devez être physiquement au Canada. Travailler à distance depuis un autre pays – même pour un employeur canadien – ne compte pas dans vos 1 095 jours.",
    q4: "Puis-je postuler avant d’atteindre exactement 1 095 jours ?",
    a4: "Non. Vous devez avoir au moins 1 095 jours crédités avant la date de votre demande. IRCC vérifiera cela et rejettera les demandes insuffisantes, même d'un seul jour.",
    q5: "Quels documents IRCC utilise-t-il pour vérifier la présence ?",
    a5: "IRCC peut demander n'importe quelle combinaison de : timbres de voyage de passeport, itinéraires de vol, déclarations de revenus (T1 générale), dossiers d'emploi, dossiers scolaires, contrats de location et relevés bancaires. Il est fortement recommandé de conserver une trace de tous les déplacements.",
    q6: "DaysToCitizen est-il un outil officiel d'IRCC ?",
    a6Before: "Non. DaysToCitizen est un outil indépendant et open source conçu pour aider les immigrants à suivre leurs propres dossiers. Il n'est pas affilié au gouvernement du Canada. Vérifiez toujours les détails de votre candidature via le responsable",
    a6Link: "IRCC",
    a6After: "site Web avant de soumettre votre candidature.",
    q7: "Mes données sont-elles privées ?",
    a7: "Oui. Les données des utilisateurs invités restent entièrement dans leur navigateur (localStorage) — rien n'est envoyé à un serveur. Les données des utilisateurs enregistrés sont stockées en toute sécurité au Canada (AWS ca-central-1) et ne sont jamais partagées ou vendues. L'application est open source et peut être auto-hébergée.",
  },
  mistakes: {
    title: "Erreurs de comptage courantes à éviter",
    m1: "En utilisant le comptage exclusif (sans compter les jours d'arrivée/de départ) : comptez toujours les deux extrémités.",
    m2: "Oubliez les courts voyages : même un week-end à l’étranger interrompt votre séquence.",
    m3: "Ne pas enregistrer le temps pré-RP : ces jours comptent à 50 % et peuvent totaliser jusqu'à 365 jours crédités.",
    m4: "En supposant que la fenêtre de 5 ans soit fixe, elle évolue avec la date de votre candidature.",
    m5: "Soumettez avant d'atteindre exactement 1 095 : attendez que le tableau de bord affiche 0 jour restant.",
  },
  cta: {
    title: "Commencez à suivre vos journées",
    subtitle: "Gratuit, privé et aucune configuration requise. Fonctionne en 23 langues.",
    button: "Journées portes ouvertes au citoyen →",
  },
};

export default help;
