import type { HelpContent } from './en';

const help: HelpContent = {
  back: "Torniamo a DaysToCitizen",
  hero: {
    title: "Come tenere traccia dei tuoi giorni per la cittadinanza canadese",
    introBefore: "Il Canada richiede l’accumulo dei residenti permanenti",
    introBold: "1.095 giorni di presenza fisica",
    introAfter: "entro un periodo di 5 anni prima di richiedere la cittadinanza. Questa guida spiega esattamente come l'IRCC conta quei giorni e come DaysToCitizen ti aiuta a monitorarli senza fogli di calcolo.",
  },
  requirement: {
    title: "Il requisito di presenza fisica dell'IRCC",
    p1Before: "Sotto il",
    p1Law: "Legge sulla cittadinanza",
    p1After: ", ogni richiedente cittadinanza deve dimostrare di essere stato fisicamente presente in Canada per almeno 1.095 giorni (3 anni) nei 5 anni immediatamente precedenti la data della domanda. Questo viene calcolato su base continuativa: la finestra di 5 anni si sposta con la data della domanda, non con un periodo di calendario fisso.",
    keyRuleTitle: "Regola fondamentale: sia il giorno di entrata che quello di uscita contano come giorni interi.",
    keyRuleBody: "Se voli a Toronto il 1 marzo e parti il 5 marzo, contano 5 giorni, non 3 o 4. Questo è uno degli errori di conteggio errati più comuni.",
    p2: "L'IRCC verifica la tua presenza utilizzando timbri sui passaporti, cronologia dei viaggi, documenti fiscali e altri documenti. Sottovalutare o sopravvalutare i propri giorni, anche accidentalmente, può comportare il rifiuto della domanda o la constatazione di false dichiarazioni.",
  },
  status: {
    title: "Giorni di residenza permanente e altri giorni di stato",
    intro: "Non tutti i giorni in Canada contano allo stesso modo. La legge sulla cittadinanza distingue tra il tempo trascorso come residente permanente e il tempo trascorso sotto altri status di immigrazione (visto per studenti, permesso di lavoro, visitatore, persona protetta, ecc.).",
    thStatus: "Stato",
    thCounts: "Conta fino a 1.095?",
    thRate: "Vota",
    prStatus: "Residente permanente",
    prCounts: "Sì",
    prRate: "1 giorno = 1 giorno",
    refugeeStatus: "Persona protetta/Rifugiato convenzionato",
    refugeeCounts: "Sì (parziale)",
    refugeeRate: "2 giorni = 1 giorno (max 365 accreditati)",
    visitorStatus: "Studente/Permesso di lavoro/Visitatore",
    visitorCounts: "Sì (parziale)",
    visitorRate: "2 giorni = 1 giorno (max 365 accreditati)",
    noneStatus: "Non autorizzato/Nessuno stato",
    noneCounts: "No",
    noneRate: "0",
    footer: "DaysToCitizen applica queste tariffe automaticamente quando accedi a ciascun soggiorno. Seleziona semplicemente il tuo stato di immigrazione per ciascun periodo e i calcoli verranno gestiti per te.",
  },
  howto: {
    title: "Come utilizzare DaysToCitizen",
    step1Title: "Apri l'app: non è richiesta la registrazione.",
    step1Body: "I tuoi soggiorni vengono salvati localmente nel tuo browser. Crea un account solo se desideri che i tuoi dati siano sincronizzati su tutti i dispositivi.",
    step2Title: "Aggiungi i tuoi soggiorni in Canada.",
    step2Body: "Inserisci la data di ingresso, la data di uscita (lascia vuoto se ti trovi attualmente in Canada) e il tuo stato di immigrazione in quel momento.",
    step3Title: "Leggi la tua dashboard.",
    step3Body: "La scheda del conto alla rovescia mostra quanti giorni in più ti servono. La barra di avanzamento mostra la finestra di 5 anni. Le schede statistiche analizzano i giorni accreditati rispetto ai giorni totali.",
    step4Title: "Aggiorna mentre viaggi.",
    step4Body: "Aggiungi un nuovo soggiorno ogni volta che torni in Canada. Il calcolo si aggiorna istantaneamente.",
  },
  faq: {
    title: "Domande frequenti",
    q1: "Conto il giorno in cui arrivo e quello in cui parto?",
    a1: "SÌ. L'IRCC conta sia il giorno di arrivo che quello di partenza come giorni interi di presenza. Un viaggio dal lunedì al venerdì dura 5 giorni, non 4 o 3. DaysToCitizen utilizza lo stesso metodo di conteggio inclusivo.",
    q2: "Cosa succederebbe se fossi in Canada prima di diventare residente permanente?",
    a2: "Il tempo trascorso in Canada prima della data di PR può essere conteggiato con una tariffa 2 per 1 (massimo 365 giorni accreditati). Seleziona \"Altro stato\" quando registri tali soggiorni e DaysToCitizen applicherà la tariffa corretta.",
    a2ExampleTitle: 'Esempio',
    a2ExampleLine1: 'Gen 2023 – Mar 2024 → Seleziona "Altro Stato" (visto/lavoro/studio). Questi 15 mesi contano al tasso di 2 a 1.',
    a2ExampleLine2: 'Mar 2024 – Gen 2026 → Seleziona "Residente Permanente". Questi 22 mesi contano per intero (1:1).',
    q3: "Lavorare da remoto per un’azienda canadese all’estero conta?",
    a3: "No. Presenza fisica significa che devi essere fisicamente in Canada. Lavorare a distanza da un altro Paese, anche per un datore di lavoro canadese, non conta ai fini dei 1.095 giorni.",
    q4: "Posso presentare domanda prima di raggiungere esattamente i 1.095 giorni?",
    a4: "No. Devi avere almeno 1.095 giorni accreditati prima della data della domanda. L'IRCC lo verificherà e rifiuterà le domande che non sono all'altezza, anche per un solo giorno.",
    q5: "Quali documenti utilizza l'IRCC per verificare la presenza?",
    a5: "L'IRCC può richiedere qualsiasi combinazione di: timbri di viaggio sul passaporto, itinerari di volo, dichiarazioni dei redditi (T1 Generale), documenti di lavoro, documenti scolastici, contratti di locazione ed estratti conto bancari. Si consiglia vivamente di tenere un registro di tutti i viaggi.",
    q6: "DaysToCitizen è uno strumento IRCC ufficiale?",
    a6Before: "No. DaysToCitizen è uno strumento indipendente e open source creato per aiutare gli immigrati a tenere traccia dei propri record. Non è affiliato al governo del Canada. Verifica sempre i dettagli della tua domanda tramite il funzionario",
    a6Link: "IRCC",
    a6After: "sito web prima di inviare la domanda.",
    q7: "I miei dati sono privati?",
    a7: "SÌ. I dati degli utenti ospiti rimangono interamente nel loro browser (localStorage): nulla viene inviato a nessun server. I dati degli utenti registrati vengono archiviati in modo sicuro in Canada (AWS ca-central-1) e non vengono mai condivisi o venduti. L'app è open source e può essere ospitata autonomamente.",
  },
  mistakes: {
    title: "Errori comuni di conteggio da evitare",
    m1: "Utilizzando il conteggio esclusivo (esclusi i giorni di arrivo/partenza): contare sempre entrambe le estremità.",
    m2: "Dimenticando i viaggi brevi: anche un fine settimana oltre confine interrompe la tua serie di vittorie.",
    m3: "Non registrare il tempo di pre-PR: quei giorni contano al 50% e possono sommare fino a 365 giorni accreditati.",
    m4: "Supponendo che la finestra di 5 anni sia fissa, si sposta con la data della domanda.",
    m5: "Invio prima di raggiungere esattamente 1.095: attendi finché la dashboard non mostra 0 giorni rimanenti.",
  },
  cta: {
    title: "Inizia a monitorare le tue giornate",
    subtitle: "Gratuito, privato e senza necessità di configurazione. Funziona in 23 lingue.",
    button: "Open DaysToCitizen→",
  },
};

export default help;
