import type { HelpContent } from './en';

const help: HelpContent = {
  back: "Powrót do DaysToCitizen",
  hero: {
    title: "Jak śledzić swoje dni w przypadku obywatelstwa kanadyjskiego",
    introBefore: "Kanada wymaga gromadzenia stałych rezydentów",
    introBold: "1095 dni fizycznej obecności",
    introAfter: "w dowolnym okresie 5 lat przed złożeniem wniosku o obywatelstwo. Ten przewodnik wyjaśnia dokładnie, jak IRCC liczy te dni i jak DaysToCitizen pomaga je śledzić bez arkuszy kalkulacyjnych.",
  },
  requirement: {
    title: "Wymóg obecności fizycznej IRCC",
    p1Before: "Pod",
    p1Law: "Ustawa o obywatelstwie",
    p1After: ", każdy ubiegający się o obywatelstwo musi udowodnić, że fizycznie przebywał w Kanadzie przez co najmniej 1095 dni (3 lata) z 5 lat bezpośrednio poprzedzających datę złożenia wniosku. Oblicza się to w sposób ciągły — 5-letnie okno przesuwa się wraz z datą złożenia wniosku, a nie stałym okresem kalendarzowym.",
    keyRuleTitle: "Kluczowa zasada: zarówno dzień wejścia, jak i dzień wyjazdu liczą się jako pełne dni.",
    keyRuleBody: "Jeśli przylecisz do Toronto 1 marca, a wylecisz 5 marca, liczy się to jako 5 dni, a nie 3 czy 4. Jest to jeden z najczęstszych błędów w błędnym liczeniu.",
    p2: "IRCC weryfikuje Twoją obecność na podstawie stempli paszportowych, historii podróży, rejestrów podatkowych i innych dokumentów. Zaniżenie lub zawyżenie liczby dni — nawet przypadkowo — może skutkować odrzuceniem wniosku lub stwierdzeniem wprowadzenia w błąd.",
  },
  status: {
    title: "Dni stałego pobytu a dni innego statusu",
    intro: "Nie wszystkie dni w Kanadzie liczą się jednakowo. Ustawa o obywatelstwie rozróżnia czas spędzony jako stały rezydent od czasu spędzonego w ramach innych statusów imigracyjnych (wiza studencka, zezwolenie na pracę, gość, osoba podlegająca ochronie itp.).",
    thStatus: "Stan",
    thCounts: "Liczy do 1095?",
    thRate: "Oceń",
    prStatus: "Stały rezydent",
    prCounts: "Tak",
    prRate: "1 dzień = 1 dzień",
    refugeeStatus: "Osoba podlegająca ochronie / uchodźca objęty konwencją",
    refugeeCounts: "Tak (częściowo)",
    refugeeRate: "2 dni = 1 dzień (maks. 365 kredytów)",
    visitorStatus: "Student/pozwolenie na pracę/gość",
    visitorCounts: "Tak (częściowo)",
    visitorRate: "2 dni = 1 dzień (maks. 365 kredytów)",
    noneStatus: "Nieautoryzowane / Brak statusu",
    noneCounts: "Nie",
    noneRate: "0",
    footer: "DaysToCitizen stosuje te stawki automatycznie po zalogowaniu każdego pobytu. Po prostu wybierz swój status imigracyjny dla każdego okresu, a obliczenia zostaną wykonane za Ciebie.",
  },
  howto: {
    title: "Jak korzystać z DaysToCitizen",
    step1Title: "Otwórz aplikację — nie jest wymagana rejestracja.",
    step1Body: "Twoje pobyty zapisywane są lokalnie w Twojej przeglądarce. Utwórz konto tylko wtedy, gdy chcesz, aby Twoje dane były synchronizowane na różnych urządzeniach.",
    step2Title: "Dodaj swoje pobyty w Kanadzie.",
    step2Body: "Wprowadź datę wjazdu, datę wyjazdu (pozostaw puste, jeśli aktualnie przebywasz w Kanadzie) oraz swój ówczesny status imigracyjny.",
    step3Title: "Przeczytaj swój pulpit nawigacyjny.",
    step3Body: "Karta odliczania pokazuje, ile jeszcze dni potrzebujesz. Pasek postępu pokazuje Twoje 5-letnie okno. Karty statystyk przedstawiają podział przyznanych dni na całkowitą liczbę dni.",
    step4Title: "Aktualizuj podczas podróży.",
    step4Body: "Dodaj nowy pobyt za każdym razem, gdy wrócisz do Kanady. Obliczenia aktualizują się natychmiast.",
  },
  faq: {
    title: "Często zadawane pytania",
    q1: "Czy liczę dzień przybycia i dzień wyjazdu?",
    a1: "Tak. IRCC liczy zarówno dzień przyjazdu, jak i dzień wyjazdu jako pełne dni obecności. Podróż od poniedziałku do piątku trwa 5 dni, a nie 4 czy 3. DaysToCitizen stosuje tę samą, włączającą metodę liczenia.",
    q2: "Co się stanie, jeśli byłem w Kanadzie przed uzyskaniem statusu rezydenta stałego?",
    a2: "Czas spędzony w Kanadzie przed datą PR może być liczony według stawki 2 za 1 (maksymalnie 365 kredytowanych dni). Podczas rejestrowania tych pobytów wybierz opcję „Inny status”, a DaysToCitizen zastosuje odpowiednią stawkę.",
    q3: "Czy praca zdalna dla kanadyjskiej firmy podczas pobytu za granicą się liczy?",
    a3: "Nie. Fizyczna obecność oznacza, że musisz fizycznie przebywać w Kanadzie. Praca zdalna z innego kraju – nawet dla kanadyjskiego pracodawcy – nie wlicza się do Twoich 1095 dni.",
    q4: "Czy mogę złożyć wniosek przed upływem dokładnie 1095 dni?",
    a4: "Nie. Musisz mieć co najmniej 1095 zaliczonych dni przed datą złożenia wniosku. IRCC zweryfikuje to i odrzuci wnioski, które spełniają wymagania nawet o jeden dzień.",
    q5: "Jakich dokumentów używa IRCC do weryfikacji obecności?",
    a5: "IRCC może zażądać dowolnej kombinacji: pieczątek podróżnych do paszportu, planów lotów, zeznań podatkowych (ogólne T1), akt zatrudnienia, dokumentów szkolnych, umów najmu i wyciągów bankowych. Zdecydowanie zaleca się prowadzenie dokumentacji wszystkich podróży.",
    q6: "Czy DaysToCitizen jest oficjalnym narzędziem IRCC?",
    a6Before: "Nie. DaysToCitizen to niezależne narzędzie o otwartym kodzie źródłowym, które ma pomóc imigrantom w śledzeniu ich własnych danych. Nie jest powiązana z rządem Kanady. Zawsze sprawdzaj szczegóły swojego wniosku za pośrednictwem urzędnika",
    a6Link: "IRCC",
    a6After: "stronie internetowej przed złożeniem wniosku.",
    q7: "Czy moje dane są prywatne?",
    a7: "Tak. Dane użytkowników-gości pozostają w całości w ich przeglądarce (localStorage) — nic nie jest wysyłane na żaden serwer. Dane zarejestrowanych użytkowników są bezpiecznie przechowywane w Kanadzie (AWS ca-central-1) i nigdy nie są udostępniane ani sprzedawane. Aplikacja jest typu open source i może być hostowana samodzielnie.",
  },
  mistakes: {
    title: "Typowe błędy w liczeniu, których należy unikać",
    m1: "Używając liczenia wyłącznego (nie licząc dni przyjazdu/odlotu) – zawsze licz oba końce.",
    m2: "Zapomnij o krótkich wycieczkach – nawet weekend za granicą przerywa twoją passę.",
    m3: "Brak rejestrowania czasu przed PR — te dni liczą się jako 50% i mogą sumować się do 365 dni zaliczonych.",
    m4: "Zakładając, że okno 5-letnie jest stałe – przesuwa się wraz z datą złożenia wniosku.",
    m5: "Przesyłanie przed osiągnięciem dokładnie 1095 — poczekaj, aż na pulpicie nawigacyjnym pojawi się 0 pozostałych dni.",
  },
  cta: {
    title: "Zacznij śledzić swoje dni",
    subtitle: "Bezpłatny, prywatny i nie wymaga konfiguracji. Działa w 23 językach.",
    button: "Dni Otwarte Dla Obywatela →",
  },
};

export default help;
