import type { HelpContent } from './en';

const help: HelpContent = {
  back: "Voltar para DaysToCitizen",
  hero: {
    title: "Como monitorar seus dias para obter a cidadania canadense",
    introBefore: "O Canadá exige que os residentes permanentes acumulem",
    introBold: "1.095 dias de presença física",
    introAfter: "dentro de qualquer período de 5 anos antes de solicitar a cidadania. Este guia explica exatamente como o IRCC conta esses dias e como o DaysToCitizen ajuda você a rastreá-los sem planilhas.",
  },
  requirement: {
    title: "O requisito de presença física do IRCC",
    p1Before: "Sob o",
    p1Law: "Lei da Cidadania",
    p1After: ", todo solicitante de cidadania deve provar que esteve fisicamente presente no Canadá por pelo menos 1.095 dias (3 anos) dos 5 anos imediatamente anteriores à data do pedido. Isso é calculado de forma contínua – a janela de 5 anos muda com a data da sua inscrição, não com um período fixo de calendário.",
    keyRuleTitle: "Regra principal: tanto o dia de entrada quanto o dia de saída contam como dias inteiros.",
    keyRuleBody: "Se você voar para Toronto em 1º de março e partir em 5 de março, isso contará como 5 dias - não 3 ou 4. Este é um dos erros de contagem mais comuns.",
    p2: "O IRCC verifica sua presença usando carimbos de passaporte, histórico de viagens, registros fiscais e outros documentos. Subestimar ou exagerar seus dias – mesmo acidentalmente – pode resultar na recusa da inscrição ou na constatação de falsas declarações.",
  },
  status: {
    title: "Dias de Residente Permanente vs. Outros Dias de Status",
    intro: "Nem todos os dias no Canadá contam igualmente. A Lei da Cidadania distingue entre o tempo passado como Residente Permanente e o tempo passado sob outros estatutos de imigração (visto de estudante, autorização de trabalho, visitante, pessoa protegida, etc.).",
    thStatus: "Estado",
    thCounts: "Conta para 1.095?",
    thRate: "Taxa",
    prStatus: "Residente Permanente",
    prCounts: "Sim",
    prRate: "1 dia = 1 dia",
    refugeeStatus: "Pessoa Protegida/Refugiado da Convenção",
    refugeeCounts: "Sim (parcial)",
    refugeeRate: "2 dias = 1 dia (máximo de 365 creditados)",
    visitorStatus: "Estudante/Permissão de Trabalho/Visitante",
    visitorCounts: "Sim (parcial)",
    visitorRate: "2 dias = 1 dia (máximo de 365 creditados)",
    noneStatus: "Não autorizado/sem status",
    noneCounts: "Não",
    noneRate: "0",
    footer: "O DaysToCitizen aplica essas tarifas automaticamente quando você registra cada estadia. Basta selecionar seu status de imigração para cada período e a matemática será feita para você.",
  },
  howto: {
    title: "Como usar o DaysToCitizen",
    step1Title: "Abra o aplicativo – não é necessária inscrição.",
    step1Body: "Suas estadias são salvas localmente no seu navegador. Crie uma conta apenas se desejar que seus dados sejam sincronizados entre dispositivos.",
    step2Title: "Adicione suas estadias no Canadá.",
    step2Body: "Insira a data de entrada, a data de saída (deixe em branco se você estiver no Canadá) e seu status de imigração no momento.",
    step3Title: "Leia seu painel.",
    step3Body: "O cartão de contagem regressiva mostra quantos dias a mais você precisa. A barra de progresso mostra sua janela de 5 anos. Os cartões de estatísticas são divididos entre os dias creditados e o total de dias.",
    step4Title: "Atualize enquanto você viaja.",
    step4Body: "Adicione uma nova estadia sempre que retornar ao Canadá. O cálculo é atualizado instantaneamente.",
  },
  faq: {
    title: "Perguntas frequentes",
    q1: "Conto o dia que chego e o dia que sai?",
    a1: "Sim. O IRCC conta o dia de chegada e o dia de partida como dias completos de presença. Uma viagem de segunda a sexta dura 5 dias, não 4 ou 3. DaysToCitizen usa o mesmo método de contagem inclusivo.",
    q2: "E se eu estivesse no Canadá antes de me tornar residente permanente?",
    a2: "O tempo passado no Canadá antes da data de RP pode contar a uma taxa de 2 por 1 (máximo de 365 dias creditados). Selecione \"Outro status\" ao registrar essas estadias e o DaysToCitizen aplicará a taxa correta.",
    a2ExampleTitle: 'Exemplo',
    a2ExampleLine1: 'Jan 2023 – Mar 2024 → Selecione "Outro Status" (visto/trabalho/estudo). Esses 15 meses contam na proporção de 2 por 1.',
    a2ExampleLine2: 'Mar 2024 – Jan 2026 → Selecione "Residente Permanente". Esses 22 meses contam integralmente (1:1).',
    q3: "Trabalhar remotamente para uma empresa canadense no exterior conta?",
    a3: "Não. Presença física significa que você deve estar fisicamente no Canadá. Trabalhar remotamente de outro país – mesmo para um empregador canadense – não conta para seus 1.095 dias.",
    q4: "Posso me inscrever antes de completar exatamente 1.095 dias?",
    a4: "Não. Você deve ter pelo menos 1.095 dias creditados antes da data de inscrição. O IRCC verificará isso e rejeitará os pedidos que forem insuficientes, mesmo que por um único dia.",
    q5: "Quais documentos o IRCC usa para verificar a presença?",
    a5: "O IRCC pode solicitar qualquer combinação de: carimbos de viagem de passaporte, itinerários de voo, declarações fiscais (T1 Geral), registros de emprego, registros escolares, contratos de arrendamento e extratos bancários. É altamente recomendável manter registros de todas as viagens.",
    q6: "O DaysToCitizen é uma ferramenta oficial do IRCC?",
    a6Before: "Não. DaysToCitizen é uma ferramenta independente e de código aberto criada para ajudar os imigrantes a rastrear seus próprios registros. Não é afiliado ao Governo do Canadá. Sempre verifique os detalhes da sua inscrição através do oficial",
    a6Link: "IRCC",
    a6After: "site antes de enviar sua inscrição.",
    q7: "Meus dados são privados?",
    a7: "Sim. Os dados dos usuários convidados permanecem inteiramente em seus navegadores (localStorage) — nada é enviado para nenhum servidor. Os dados dos usuários registrados são armazenados de forma segura no Canadá (AWS ca-central-1) e nunca são compartilhados ou vendidos. O aplicativo é de código aberto e pode ser auto-hospedado.",
  },
  mistakes: {
    title: "Erros comuns de contagem a serem evitados",
    m1: "Usando contagem exclusiva (sem incluir dias de chegada/partida) — conte sempre os dois extremos.",
    m2: "Esquecer viagens curtas – até mesmo um fim de semana do outro lado da fronteira quebra sua sequência.",
    m3: "Não registrar o tempo pré-RP – esses dias contam em 50% e podem somar 365 dias creditados.",
    m4: "Supondo que a janela de 5 anos seja fixa – ela muda com a data da sua inscrição.",
    m5: "Enviando antes de atingir exatamente 1.095 – espere até que o painel mostre 0 dias restantes.",
  },
  cta: {
    title: "Comece a monitorar seus dias",
    subtitle: "Gratuito, privado e sem necessidade de configuração. Funciona em 23 idiomas.",
    button: "Dias Abertos ao Cidadão →",
  },
};

export default help;
