import type { HelpContent } from './en';

const help: HelpContent = {
  back: "Înapoi la DaysToCitizen",
  hero: {
    title: "Cum să vă urmăriți zilele pentru cetățenia canadiană",
    introBefore: "Canada solicită rezidenților permanenți să se acumuleze",
    introBold: "1.095 de zile de prezență fizică",
    introAfter: "în orice perioadă de 5 ani înainte de a solicita cetățenia. Acest ghid explică exact cum numără IRCC acele zile și cum DaysToCitizen vă ajută să le urmăriți fără foi de calcul.",
  },
  requirement: {
    title: "Cerința IRCC privind prezența fizică",
    p1Before: "Sub",
    p1Law: "Legea cetăţeniei",
    p1After: ", fiecare solicitant de cetățenie trebuie să dovedească că a fost prezent fizic în Canada timp de cel puțin 1.095 de zile (3 ani) din cei 5 ani imediat anteriori datei cererii. Acesta este calculat pe o bază continuă — fereastra de 5 ani se mută odată cu data cererii dvs., nu cu o perioadă calendaristică fixă.",
    keyRuleTitle: "Regula cheie: atât ziua în care intri, cât și ziua în care ieși, sunt considerate zile întregi.",
    keyRuleBody: "Dacă zburați în Toronto pe 1 martie și zburați pe 5 martie, înseamnă 5 zile, nu 3 sau 4. Aceasta este una dintre cele mai frecvente greșeli de numărare greșită.",
    p2: "IRCC vă verifică prezența folosind ștampile de pașapoarte, istoricul călătoriilor, registrele fiscale și alte documente. Subestimarea sau exagerarea zilelor tale – chiar și accidental – poate duce la refuzul cererii sau la constatarea unei declarații greșite.",
  },
  status: {
    title: "Zile de rezident permanent versus alte zile de statut",
    intro: "Nu toate zilele din Canada contează la fel. Legea cetățeniei face distincție între timpul petrecut ca rezident permanent și timpul petrecut în alte statuturi de imigrare (viză de student, permis de muncă, vizitator, persoană protejată etc.).",
    thStatus: "Stare",
    thCounts: "Contează până la 1.095?",
    thRate: "Rata",
    prStatus: "Rezident permanent",
    prCounts: "Da",
    prRate: "1 zi = 1 zi",
    refugeeStatus: "Persoană protejată / Refugiat din Convenție",
    refugeeCounts: "Da (parțial)",
    refugeeRate: "2 zile = 1 zi (maxim 365 creditate)",
    visitorStatus: "Student / Permis de muncă / Vizitator",
    visitorCounts: "Da (parțial)",
    visitorRate: "2 zile = 1 zi (maxim 365 creditate)",
    noneStatus: "Neautorizat/Fără stare",
    noneCounts: "Nu",
    noneRate: "0",
    footer: "DaysToCitizen aplică aceste tarife automat atunci când vă înregistrați fiecare sejur. Pur și simplu selectați statutul dvs. de imigrare pentru fiecare perioadă și calculele sunt gestionate pentru dvs.",
  },
  howto: {
    title: "Cum să utilizați DaysToCitizen",
    step1Title: "Deschideți aplicația - nu este necesară înregistrarea.",
    step1Body: "Sejururile dvs. sunt salvate local în browser. Creați un cont numai dacă doriți ca datele dvs. să fie sincronizate între dispozitive.",
    step2Title: "Adaugă-ți șederea în Canada.",
    step2Body: "Introduceți data intrării, data ieșirii (lăsați necompletat dacă vă aflați în prezent în Canada) și statutul dvs. de imigrare la momentul respectiv.",
    step3Title: "Citiți tabloul de bord.",
    step3Body: "Cardul de numărătoare inversă arată de câte zile mai aveți nevoie. Bara de progres arată fereastra dvs. de 5 ani. Cardurile cu statistici defalc creditate față de numărul total de zile.",
    step4Title: "Actualizați pe măsură ce călătoriți.",
    step4Body: "Adăugați o nouă ședere de fiecare dată când vă întoarceți în Canada. Calculul se actualizează instantaneu.",
  },
  faq: {
    title: "Întrebări frecvente",
    q1: "Număr ziua în care ajung și ziua în care plec?",
    a1: "Da. IRCC consideră zile întregi de prezență atât ziua sosirii, cât și ziua plecării. O călătorie de luni până vineri este de 5 zile, nu de 4 sau 3. DaysToCitizen folosește aceeași metodă de numărare inclusivă.",
    q2: "Ce se întâmplă dacă aș fi fost în Canada înainte de a deveni rezident permanent?",
    a2: "Timpul petrecut în Canada înainte de data dvs. de PR poate conta la o rată de 2 pentru 1 (maximum 365 de zile creditate). Selectați „Altă stare” când înregistrați acele sejururi și DaysToCitizen va aplica rata corectă.",
    q3: "Lucrul de la distanță pentru o companie canadiană în străinătate contează?",
    a3: "Nu. Prezența fizică înseamnă că trebuie să fii fizic în Canada. Lucrul de la distanță dintr-o altă țară – chiar și pentru un angajator canadian – nu ia în calcul cele 1.095 de zile.",
    q4: "Pot aplica înainte de a ajunge exact la 1.095 de zile?",
    a4: "Nu. Trebuie să aveți cel puțin 1.095 de zile creditate înainte de data cererii. IRCC va verifica acest lucru și va respinge cererile care nu sunt insuficiente, chiar și cu o singură zi.",
    q5: "Ce documente folosește IRCC pentru a verifica prezența?",
    a5: "IRCC poate solicita orice combinație de: ștampile de călătorie din pașaport, itinerarii de zbor, declarații fiscale (T1 General), dosare de angajare, dosare școlare, contracte de închiriere și extrase de cont. Păstrarea înregistrărilor tuturor călătoriilor este insistent recomandată.",
    q6: "DaysToCitizen este un instrument oficial IRCC?",
    a6Before: "Nu. DaysToCitizen este un instrument independent, open-source, creat pentru a ajuta imigranții să își urmărească propriile evidențe. Nu este afiliat cu Guvernul Canadei. Verificați întotdeauna detaliile aplicației prin intermediul oficialului",
    a6Link: "IRCC",
    a6After: "site-ul web înainte de a trimite cererea.",
    q7: "Datele mele sunt private?",
    a7: "Da. Datele utilizatorilor invitați rămân în întregime în browserul lor (localStorage) - nimic nu este trimis la niciun server. Datele utilizatorilor înregistrați sunt stocate în siguranță în Canada (AWS ca-central-1) și nu sunt niciodată partajate sau vândute. Aplicația este open-source și poate fi auto-găzduită.",
  },
  mistakes: {
    title: "Greșeli frecvente de numărare de evitat",
    m1: "Folosind contorizarea exclusivă (fără a include zilele de sosire/plecare) - numărați întotdeauna ambele capete.",
    m2: "Uitarea de călătorii scurte - chiar și un weekend peste graniță vă întrerupe șirul.",
    m3: "Nu se înregistrează timp înainte de PR - acele zile contează la 50% și pot adăuga până la 365 de zile creditate.",
    m4: "Presupunând că fereastra de 5 ani este fixă - se mută odată cu data cererii dvs.",
    m5: "Trimiteți înainte de a atinge exact 1.095 - așteptați până când tabloul de bord arată 0 zile rămase.",
  },
  cta: {
    title: "Începeți să vă urmăriți zilele",
    subtitle: "Gratuit, privat și nu necesită configurare. Funcționează în 23 de limbi.",
    button: "Zilele deschise către cetățean →",
  },
};

export default help;
