import type { HelpContent } from './en';

const help: HelpContent = {
  back: "Bumalik sa DaysToCitizen",
  hero: {
    title: "Paano Subaybayan ang Iyong Mga Araw para sa Canadian Citizenship",
    introBefore: "Kinakailangan ng Canada ang mga Permanenteng Residente na mag-ipon",
    introBold: "1,095 araw ng pisikal na presensya",
    introAfter: "sa loob ng anumang 5 taon bago mag-apply para sa pagkamamamayan. Ang gabay na ito ay eksaktong nagpapaliwanag kung paano binibilang ng IRCC ang mga araw na iyon at kung paano ka tinutulungan ng DaysToCitizen na subaybayan ang mga ito nang walang mga spreadsheet.",
  },
  requirement: {
    title: "Ang Kinakailangang Pisikal na Presensya ng IRCC",
    p1Before: "Sa ilalim ng",
    p1Law: "Batas sa Pagkamamamayan",
    p1After: ", dapat patunayan ng bawat aplikante ng citizenship na sila ay pisikal na naroroon sa Canada nang hindi bababa sa 1,095 araw (3 taon) sa loob ng 5 taon kaagad bago ang petsa ng kanilang aplikasyon. Ito ay kinakalkula sa isang rolling basis — ang 5-taong palugit ay lilipat kasama ng petsa ng iyong aplikasyon, hindi isang nakapirming panahon ng kalendaryo.",
    keyRuleTitle: "Pangunahing panuntunan: ang araw na pumasok ka at ang araw na umalis ka ay binibilang bilang mga buong araw.",
    keyRuleBody: "Kung lilipad ka sa Toronto sa Marso 1 at lilipad sa Marso 5, mabibilang iyon bilang 5 araw — hindi 3 o 4. Ito ang isa sa mga pinakakaraniwang pagkakamali sa pagbilang.",
    p2: "Bine-verify ng IRCC ang iyong presensya gamit ang mga passport stamp, history ng paglalakbay, mga talaan ng buwis, at iba pang mga dokumento. Ang pag-understating o pag-overstate ng iyong mga araw — kahit na hindi sinasadya — ay maaaring magresulta sa pagtanggi sa aplikasyon o paghahanap ng maling representasyon.",
  },
  status: {
    title: "Permanent Resident Days vs. Other Status Days",
    intro: "Hindi lahat ng araw sa Canada ay pantay na binibilang. Tinutukoy ng Citizenship Act ang pagitan ng oras na ginugol bilang isang Permanent Resident at oras na ginugol sa ilalim ng ibang mga katayuan sa imigrasyon (student visa, work permit, bisita, protektadong tao, atbp.).",
    thStatus: "Katayuan",
    thCounts: "Nagbibilang ng 1,095?",
    thRate: "Rate",
    prStatus: "Permanenteng Residente",
    prCounts: "Oo",
    prRate: "1 araw = 1 araw",
    refugeeStatus: "Protektadong Tao / Convention Refugee",
    refugeeCounts: "Oo (bahagyang)",
    refugeeRate: "2 araw = 1 araw (max 365 na kredito)",
    visitorStatus: "Student / Work Permit / Bisita",
    visitorCounts: "Oo (bahagyang)",
    visitorRate: "2 araw = 1 araw (max 365 na kredito)",
    noneStatus: "Hindi awtorisado / Walang Katayuan",
    noneCounts: "Hindi",
    noneRate: "0",
    footer: "Awtomatikong inilalapat ng DaysToCitizen ang mga rate na ito kapag nag-log ka sa bawat pananatili. Piliin lamang ang iyong katayuan sa imigrasyon para sa bawat panahon at ang matematika ay hahawakan para sa iyo.",
  },
  howto: {
    title: "Paano Gamitin ang DaysToCitizen",
    step1Title: "Buksan ang app — walang kinakailangang pag-signup.",
    step1Body: "Ang iyong mga pananatili ay lokal na naka-save sa iyong browser. Gumawa lang ng account kung gusto mong ma-sync ang iyong data sa mga device.",
    step2Title: "Idagdag ang iyong mga pananatili sa Canada.",
    step2Body: "Ilagay ang petsa ng pagpasok, petsa ng paglabas (iwang blangko kung kasalukuyan kang nasa Canada), at ang iyong katayuan sa imigrasyon sa panahong iyon.",
    step3Title: "Basahin ang iyong dashboard.",
    step3Body: "Ipinapakita ng countdown card kung ilang araw pa ang kailangan mo. Ipinapakita ng progress bar ang iyong 5-taong window. Pinaghihiwa-hiwalay ng mga stats card ang kredito kumpara sa kabuuang araw.",
    step4Title: "Mag-update habang naglalakbay ka.",
    step4Body: "Magdagdag ng bagong pananatili sa tuwing babalik ka sa Canada. Ang pagkalkula ay na-update kaagad.",
  },
  faq: {
    title: "Mga Madalas Itanong",
    q1: "Binibilang ko ba ang araw na dumating ako at ang araw na aalis ako?",
    a1: "Oo. Parehong binibilang ng IRCC ang araw ng pagdating at ang araw ng pag-alis bilang buong araw ng presensya. Ang isang biyahe mula Lunes hanggang Biyernes ay 5 araw, hindi 4 o 3. Ginagamit ng DaysToCitizen ang parehong inclusive na paraan ng pagbibilang.",
    q2: "Paano kung nasa Canada ako bago naging Permanent Resident?",
    a2: "Ang oras na ginugol sa Canada bago ang petsa ng iyong PR ay maaaring mabilang sa 2-for-1 na rate (maximum na 365 na kredito na araw). Piliin ang \"Iba pang status\" kapag nagla-log sa mga pananatili na iyon at ilalapat ng DaysToCitizen ang tamang rate.",
    q3: "Mabibilang ba ang pagtatrabaho nang malayuan para sa isang kumpanya sa Canada habang nasa ibang bansa?",
    a3: "Hindi. Ang ibig sabihin ng pisikal na presensya ay nasa Canada ka. Ang pagtatrabaho nang malayuan mula sa ibang bansa — kahit na para sa isang Canadian employer — ay hindi binibilang sa iyong 1,095 araw.",
    q4: "Maaari ba akong mag-apply bago maabot ang eksaktong 1,095 araw?",
    a4: "Hindi. Dapat ay mayroon kang hindi bababa sa 1,095 na kredito na araw bago ang petsa ng iyong aplikasyon. Ibe-verify ito ng IRCC at tatanggihan ang mga aplikasyon na kulang, kahit sa isang araw.",
    q5: "Anong mga dokumento ang ginagamit ng IRCC para i-verify ang presensya?",
    a5: "Maaaring humiling ang IRCC ng anumang kumbinasyon ng: mga passport travel stamp, flight itineraries, tax returns (T1 General), mga talaan ng trabaho, mga rekord ng paaralan, mga kasunduan sa pag-upa, at mga bank statement. Ang pag-iingat ng mga talaan ng lahat ng paglalakbay ay lubos na inirerekomenda.",
    q6: "Ang DaysToCitizen ba ay isang opisyal na tool ng IRCC?",
    a6Before: "Hindi. Ang DaysToCitizen ay isang independiyente, open-source na tool na binuo upang tulungan ang mga imigrante na subaybayan ang kanilang sariling mga tala. Hindi ito kaakibat sa Gobyerno ng Canada. Palaging i-verify ang mga detalye ng iyong aplikasyon sa pamamagitan ng opisyal",
    a6Link: "IRCC",
    a6After: "website bago isumite ang iyong aplikasyon.",
    q7: "Pribado ba ang aking data?",
    a7: "Oo. Ang data ng mga bisitang user ay ganap na nananatili sa kanilang browser (localStorage) — walang ipinapadala sa anumang server. Ang data ng mga rehistradong user ay ligtas na nakaimbak sa Canada (AWS ca-central-1) at hindi kailanman ibinabahagi o ibinebenta. Ang app ay open-source at maaaring self-host.",
  },
  mistakes: {
    title: "Mga Karaniwang Pagkakamali sa Pagbibilang na Dapat Iwasan",
    m1: "Paggamit ng eksklusibong pagbibilang (hindi kasama ang mga araw ng pagdating/pag-alis) — palaging bilangin ang magkabilang dulo.",
    m2: "Ang paglimot sa mga maiikling biyahe — kahit isang katapusan ng linggo sa kabila ng hangganan ay pinuputol ang iyong streak.",
    m3: "Hindi nagla-log bago ang PR-PR — ang mga araw na iyon ay binibilang sa 50% at maaaring magdagdag ng hanggang 365 na kredito na araw.",
    m4: "Ipagpalagay na ang 5-taong palugit ay naayos — ito ay gumagalaw kasama ng petsa ng iyong aplikasyon.",
    m5: "Pagsusumite bago pindutin ang eksaktong 1,095 — maghintay hanggang ang dashboard ay magpakita ng 0 araw na natitira.",
  },
  cta: {
    title: "Simulan ang Pagsubaybay sa Iyong Mga Araw",
    subtitle: "Libre, pribado, at walang kinakailangang setup. Gumagana sa 23 mga wika.",
    button: "Open DaysToCitizen →",
  },
};

export default help;
