import type { HelpContent } from './en';

const help: HelpContent = {
  back: "DaysToCitizen'e geri dön",
  hero: {
    title: "Kanada Vatandaşlığı İçin Günlerinizi Nasıl Takip Edebilirsiniz?",
    introBefore: "Kanada Daimi Oturma İzni Olan Kişilerin birikim yapmasını şart koşuyor",
    introBold: "1.095 gün fiziksel mevcudiyet",
    introAfter: "Vatandaşlığa başvurmadan önce herhangi bir 5 yıllık süre içinde. Bu kılavuz, IRCC'nin bu günleri tam olarak nasıl saydığını ve DaysToCitizen'in elektronik tablolar olmadan bunları takip etmenize nasıl yardımcı olduğunu tam olarak açıklamaktadır.",
  },
  requirement: {
    title: "IRCC Fiziksel Mevcudiyet Gereksinimi",
    p1Before: "Altında",
    p1Law: "Vatandaşlık Yasası",
    p1After: ", her vatandaşlık başvurusu sahibi, başvuru tarihinden hemen önceki 5 yılın en az 1.095 günü (3 yıl) boyunca fiziksel olarak Kanada'da bulunduğunu kanıtlamalıdır. Bu, sürekli olarak hesaplanır; 5 yıllık süre, sabit bir takvim dönemiyle değil, başvuru tarihinizle birlikte hareket eder.",
    keyRuleTitle: "Temel kural: hem girdiğiniz gün hem de ayrıldığınız gün tam gün olarak sayılır.",
    keyRuleBody: "1 Mart'ta Toronto'ya uçarsanız ve 5 Mart'ta ayrılırsanız, bu 3 veya 4 değil, 5 gün sayılır. Bu, en yaygın yanlış sayma hatalarından biridir.",
    p2: "IRCC, pasaport pullarını, seyahat geçmişini, vergi kayıtlarını ve diğer belgeleri kullanarak varlığınızı doğrular. Günlerinizi olduğundan az veya fazla göstermek (kazayla bile olsa) başvurunun reddedilmesine veya yanlış beyanın tespit edilmesine yol açabilir.",
  },
  status: {
    title: "Daimi İkamet Günleri ve Diğer Statü Günleri Karşılaştırması",
    intro: "Kanada'daki tüm günler eşit sayılmaz. Vatandaşlık Yasası, Daimi Oturma İzni sahibi olarak geçirilen süre ile diğer göçmenlik statüleri (öğrenci vizesi, çalışma izni, ziyaretçi, korunan kişi vb.) kapsamında geçirilen süre arasında ayrım yapmaktadır.",
    thStatus: "Durum",
    thCounts: "1.095'e doğru sayılır mı?",
    thRate: "Oran",
    prStatus: "Daimi Yerleşik",
    prCounts: "Evet",
    prRate: "1 gün = 1 gün",
    refugeeStatus: "Korunan Kişi / Sözleşme Mültecisi",
    refugeeCounts: "Evet (kısmi)",
    refugeeRate: "2 gün = 1 gün (maks. 365 kredi)",
    visitorStatus: "Öğrenci / Çalışma İzni / Ziyaretçi",
    visitorCounts: "Evet (kısmi)",
    visitorRate: "2 gün = 1 gün (maks. 365 kredi)",
    noneStatus: "Yetkisiz / Durum Yok",
    noneCounts: "Hayır",
    noneRate: "0",
    footer: "DaysToCitizen, her konaklamanızı kaydettiğinizde bu oranları otomatik olarak uygular. Her dönem için göçmenlik durumunuzu seçmeniz yeterlidir; matematik sizin için halledilir.",
  },
  howto: {
    title: "DaysToCitizen Nasıl Kullanılır?",
    step1Title: "Uygulamayı açın; kaydolmanıza gerek yok.",
    step1Body: "Konaklamalarınız tarayıcınıza yerel olarak kaydedilir. Yalnızca verilerinizin cihazlar arasında senkronize edilmesini istiyorsanız bir hesap oluşturun.",
    step2Title: "Kanada'daki kalışlarınızı ekleyin.",
    step2Body: "Giriş tarihini, çıkış tarihini (şu anda Kanada'daysanız boş bırakın) ve o andaki göçmenlik durumunuzu girin.",
    step3Title: "Kontrol panelinizi okuyun.",
    step3Body: "Geri sayım kartı kaç güne daha ihtiyacınız olduğunu gösterir. İlerleme çubuğu 5 yıllık pencerenizi gösterir. İstatistik kartları, kredilendirilen günlerin toplam günlere göre dökümünü yapar.",
    step4Title: "Seyahat ederken güncelleyin.",
    step4Body: "Kanada'ya her döndüğünüzde yeni bir konaklama ekleyin. Hesaplama anında güncellenir.",
  },
  faq: {
    title: "Sıkça Sorulan Sorular",
    q1: "Geldiğim günü ve ayrılacağım günü sayıyor muyum?",
    a1: "Evet. IRCC hem varış gününü hem de ayrılış gününü tam mevcudiyet günleri olarak sayar. Pazartesi'den Cuma'ya bir yolculuk 4 veya 3 değil 5 gündür. DaysToCitizen aynı kapsayıcı sayma yöntemini kullanır.",
    q2: "Daimi Oturma İzni olmadan önce Kanada'da olsaydım ne olurdu?",
    a2: "PR tarihinizden önce Kanada'da geçirdiğiniz süre, 1'e 2 oranında sayılabilir (maksimum 365 kredili gün). Bu konaklamaları kaydederken \"Diğer durum\"u seçtiğinizde DaysToCitizen doğru ücreti uygulayacaktır.",
    a2ExampleTitle: 'Örnek',
    a2ExampleLine1: 'Oca 2023 – Mar 2024 → "Diğer Statü" seçeneğini seçin (vize/çalışma/öğrenci). Bu 15 ay 2\'ye 1 oranında sayılır.',
    a2ExampleLine2: 'Mar 2024 – Oca 2026 → "Daimi Oturum İzni" seçeneğini seçin. Bu 22 ay tam olarak sayılır (1:1).',
    q3: "Yurt dışındayken Kanadalı bir şirket için uzaktan çalışmak sayılır mı?",
    a3: "Hayır. Fiziksel mevcudiyet, fiziksel olarak Kanada'da olmanız gerektiği anlamına gelir. Başka bir ülkeden uzaktan çalışmak (Kanadalı bir işveren için bile) 1.095 gününüz kapsamında sayılmaz.",
    q4: "Tam olarak 1.095 güne ulaşmadan başvuru yapabilir miyim?",
    a4: "Hayır. Başvuru tarihinizden önce en az 1.095 kredi gününüz olması gerekir. IRCC bunu doğrulayacak ve bir gün bile olsa yetersiz kalan başvuruları reddedecektir.",
    q5: "IRCC varlığını doğrulamak için hangi belgeleri kullanıyor?",
    a5: "IRCC aşağıdakilerin herhangi bir kombinasyonunu talep edebilir: pasaport seyahat damgaları, uçuş güzergahları, vergi beyannameleri (T1 Genel), istihdam kayıtları, okul kayıtları, kira sözleşmeleri ve banka ekstreleri. Tüm seyahatlerin kayıtlarının tutulması şiddetle tavsiye edilir.",
    q6: "DaysToCitizen resmi bir IRCC aracı mıdır?",
    a6Before: "Hayır. DaysToCitizen, göçmenlerin kendi kayıtlarını takip etmelerine yardımcı olmak için oluşturulmuş bağımsız, açık kaynaklı bir araçtır. Kanada Hükümeti'ne bağlı değildir. Başvuru ayrıntılarınızı her zaman yetkili aracılığıyla doğrulayın",
    a6Link: "IRCC",
    a6After: "Başvurunuzu göndermeden önce web sitesi.",
    q7: "Verilerim gizli mi?",
    a7: "Evet. Konuk kullanıcıların verileri tamamen tarayıcılarında (localStorage) kalır; hiçbir sunucuya hiçbir şey gönderilmez. Kayıtlı kullanıcıların verileri Kanada'da (AWS ca-central-1) güvenli bir şekilde saklanır ve asla paylaşılmaz veya satılmaz. Uygulama açık kaynaklıdır ve kendi kendine barındırılabilir.",
  },
  mistakes: {
    title: "Kaçınılması Gereken Yaygın Sayım Hataları",
    m1: "Özel sayımı kullanarak (varış/ayrılış günlerini hariç) her zaman her iki ucu da sayın.",
    m2: "Kısa gezileri unutun; sınırı geçen bir hafta sonu bile serinizi bozar.",
    m3: "PR öncesi sürenin kaydedilmemesi — bu günler %50 olarak sayılır ve 365'e kadar kredilendirilen gün ekleyebilir.",
    m4: "5 yıllık sürenin sabit olduğunu varsayarsak başvuru tarihinizle birlikte hareket eder.",
    m5: "Tam olarak 1.095'e ulaşmadan önce gönderim yapın; kontrol panelinde kalan 0 gün görünene kadar bekleyin.",
  },
  cta: {
    title: "Günlerinizi Takip Etmeye Başlayın",
    subtitle: "Ücretsiz, özel ve kurulum gerektirmez. 23 dilde çalışır.",
    button: "DaysToCitizen'ı açın →",
  },
};

export default help;
