import type { HelpContent } from './en';

const help: HelpContent = {
  back: "Quay lại DaysToCitizen",
  hero: {
    title: "Cách theo dõi ngày của bạn để có quốc tịch Canada",
    introBefore: "Canada yêu cầu Thường trú nhân phải tích lũy",
    introBold: "1.095 ngày hiện diện thực tế",
    introAfter: "trong khoảng thời gian 5 năm bất kỳ trước khi nộp đơn xin quốc tịch. Hướng dẫn này giải thích chính xác cách IRCC tính những ngày đó và cách DaysToCitizen giúp bạn theo dõi chúng mà không cần bảng tính.",
  },
  requirement: {
    title: "Yêu cầu hiện diện vật lý của IRCC",
    p1Before: "Dưới",
    p1Law: "Đạo luật công dân",
    p1After: ", mọi người nộp đơn xin quốc tịch phải chứng minh rằng họ đã có mặt thực tế ở Canada ít nhất 1.095 ngày (3 năm) trong 5 năm ngay trước ngày nộp đơn. Điều này được tính toán trên cơ sở luân phiên - thời hạn 5 năm di chuyển theo ngày nộp đơn của bạn chứ không phải theo khoảng thời gian cố định.",
    keyRuleTitle: "Nguyên tắc chính: cả ngày bạn vào và ngày bạn về đều được tính là cả ngày.",
    keyRuleBody: "Nếu bạn bay đến Toronto vào ngày 1 tháng 3 và bay đi vào ngày 5 tháng 3, thời gian đó được tính là 5 ngày — không phải 3 hay 4. Đây là một trong những lỗi đếm sai phổ biến nhất.",
    p2: "IRCC xác minh sự hiện diện của bạn bằng tem hộ chiếu, lịch sử du lịch, hồ sơ thuế và các tài liệu khác. Nói quá hoặc nói quá về những ngày của bạn - thậm chí là vô tình - có thể dẫn đến việc từ chối đơn đăng ký hoặc bị phát hiện là trình bày sai.",
  },
  status: {
    title: "Ngày thường trú so với ngày tình trạng khác",
    intro: "Không phải tất cả các ngày ở Canada đều được tính như nhau. Đạo luật Công dân phân biệt giữa thời gian dành cho Thường trú nhân và thời gian dành cho các tình trạng nhập cư khác (thị thực sinh viên, giấy phép lao động, khách du lịch, người được bảo vệ, v.v.).",
    thStatus: "Trạng thái",
    thCounts: "Đếm tới 1.095?",
    thRate: "tỷ lệ",
    prStatus: "Thường trú nhân",
    prCounts: "Có",
    prRate: "1 ngày = 1 ngày",
    refugeeStatus: "Người được bảo vệ / Người tị nạn theo hội nghị",
    refugeeCounts: "Có (một phần)",
    refugeeRate: "2 ngày = 1 ngày (tín dụng tối đa 365)",
    visitorStatus: "Sinh viên / Giấy phép làm việc / Du khách",
    visitorCounts: "Có (một phần)",
    visitorRate: "2 ngày = 1 ngày (tín dụng tối đa 365)",
    noneStatus: "Không được phép / Không có trạng thái",
    noneCounts: "Không",
    noneRate: "0",
    footer: "DaysToCitizen tự động áp dụng các mức giá này khi bạn đăng nhập mỗi lần lưu trú. Chỉ cần chọn tình trạng nhập cư của bạn cho từng thời kỳ và phép toán sẽ được xử lý cho bạn.",
  },
  howto: {
    title: "Cách sử dụng DaysToCitizen",
    step1Title: "Mở ứng dụng - không cần đăng ký.",
    step1Body: "Thời gian lưu trú của bạn được lưu cục bộ trong trình duyệt của bạn. Chỉ tạo tài khoản nếu bạn muốn dữ liệu của mình được đồng bộ hóa trên các thiết bị.",
    step2Title: "Thêm thời gian lưu trú của bạn ở Canada.",
    step2Body: "Nhập ngày nhập cảnh, ngày xuất cảnh (để trống nếu bạn hiện đang ở Canada) và tình trạng nhập cư của bạn tại thời điểm đó.",
    step3Title: "Đọc bảng điều khiển của bạn.",
    step3Body: "Thẻ đếm ngược cho biết bạn cần thêm bao nhiêu ngày nữa. Thanh tiến trình hiển thị khoảng thời gian 5 năm của bạn. Thẻ thống kê chia nhỏ số tiền được ghi có so với tổng số ngày.",
    step4Title: "Cập nhật khi bạn đi du lịch.",
    step4Body: "Thêm thời gian lưu trú mới mỗi khi bạn quay trở lại Canada. Việc tính toán cập nhật ngay lập tức.",
  },
  faq: {
    title: "Câu hỏi thường gặp",
    q1: "Tôi có đếm ngày tôi đến và ngày tôi đi không?",
    a1: "Đúng. IRCC tính cả ngày đến và ngày khởi hành là những ngày hiện diện đầy đủ. Chuyến đi từ Thứ Hai đến Thứ Sáu là 5 ngày chứ không phải 4 hay 3. DaysToCitizen sử dụng cùng một phương pháp đếm bao gồm này.",
    q2: "Điều gì sẽ xảy ra nếu tôi ở Canada trước khi trở thành Thường trú nhân?",
    a2: "Thời gian ở Canada trước ngày PR của bạn có thể được tính theo tỷ lệ 2 trên 1 (tối đa 365 ngày được ghi có). Chọn \"Trạng thái khác\" khi ghi lại những lần lưu trú đó và DaysToCitizen sẽ áp dụng mức giá chính xác.",
    a2ExampleTitle: 'Ví dụ',
    a2ExampleLine1: 'Tháng 1/2023 – Tháng 3/2024 → Chọn "Trạng thái khác" (visa/làm việc/học tập). 15 tháng này tính theo tỷ lệ 2 lấy 1.',
    a2ExampleLine2: 'Tháng 3/2024 – Tháng 1/2026 → Chọn "Thường trú nhân". 22 tháng này tính đầy đủ (1:1).',
    q3: "Làm việc từ xa cho một công ty Canada khi ở nước ngoài có được tính không?",
    a3: "Không. Sự hiện diện thực tế có nghĩa là bạn phải có mặt ở Canada. Làm việc từ xa từ một quốc gia khác - ngay cả đối với chủ lao động ở Canada - không được tính vào 1.095 ngày của bạn.",
    q4: "Tôi có thể nộp đơn trước khi đạt đúng 1.095 ngày không?",
    a4: "Không. Bạn phải có ít nhất 1.095 ngày ghi có trước ngày nộp đơn. IRCC sẽ xác minh điều này và từ chối các đơn đăng ký không đủ hồ sơ, thậm chí chỉ trong một ngày.",
    q5: "IRCC sử dụng những tài liệu nào để xác minh sự hiện diện?",
    a5: "IRCC có thể yêu cầu bất kỳ sự kết hợp nào của: tem du lịch hộ chiếu, hành trình chuyến bay, tờ khai thuế (T1 General), hồ sơ việc làm, hồ sơ trường học, hợp đồng cho thuê và bảng sao kê ngân hàng. Nên lưu giữ hồ sơ về tất cả các chuyến đi.",
    q6: "DaysToCitizen có phải là công cụ IRCC chính thức không?",
    a6Before: "Không. DaysToCitizen là một công cụ nguồn mở, độc lập được xây dựng để giúp người nhập cư theo dõi hồ sơ của chính họ. Nó không liên kết với Chính phủ Canada. Luôn xác minh chi tiết đơn đăng ký của bạn thông qua trang web chính thức",
    a6Link: "IRCC",
    a6After: "trang web trước khi gửi đơn đăng ký của bạn.",
    q7: "Dữ liệu của tôi có riêng tư không?",
    a7: "Đúng. Dữ liệu của người dùng khách hoàn toàn nằm trong trình duyệt của họ (localStorage) — không có gì được gửi đến bất kỳ máy chủ nào. Dữ liệu của người dùng đã đăng ký được lưu trữ an toàn ở Canada (AWS ca-central-1) và không bao giờ được chia sẻ hoặc bán. Ứng dụng này là nguồn mở và có thể tự lưu trữ.",
  },
  mistakes: {
    title: "Những lỗi đếm phổ biến cần tránh",
    m1: "Sử dụng cách tính riêng (không bao gồm ngày đến/đi) - luôn tính cả hai đầu.",
    m2: "Việc quên đi những chuyến đi ngắn ngày - ngay cả một ngày cuối tuần xuyên biên giới cũng sẽ phá vỡ kỷ lục của bạn.",
    m3: "Không ghi lại thời gian trước PR - những ngày đó được tính là 50% và có thể cộng lại lên tới 365 ngày được ghi có.",
    m4: "Giả sử khoảng thời gian 5 năm là cố định - nó sẽ di chuyển theo ngày nộp đơn của bạn.",
    m5: "Gửi trước khi đạt chính xác 1.095 - đợi cho đến khi trang tổng quan hiển thị còn 0 ngày.",
  },
  cta: {
    title: "Bắt đầu theo dõi ngày của bạn",
    subtitle: "Miễn phí, riêng tư và không cần thiết lập. Hoạt động bằng 23 ngôn ngữ.",
    button: "Mở DaysToCitizen →",
  },
};

export default help;
